- hosts: demo
  become: true
  become_user: ec2-user
  connection: ssh
  tasks: 
     - name: copy files
       copy: src=/home/ec2-user/Deployment.yml dest=/opt
     - name: copy
       copy: src=/home/ec2-user/Service.yml dest=/opt  
     - name: start objects
       command: kubectl delete -f /opt/Deployment.yml
     - name: start object
       command: kubectl delete -f /opt/Service.yml   
