- hosts: demo
  become: true
  become_user: root
  connection: ssh
  tasks: 
     - name: copy files
       copy: src=/home/ec2-user/Deployment.yml dest=/home/ec2-user
     - name: copy
       copy: src=/home/ec2-user/Service.yml dest=/home/ec2-user
     - name: chmod
       command: chmod 777 /home/ec2-user/Deployment.yml
     - name: start objects
       command: kubectl delete -f /home/ec2-user/Deployment.yml
     - name: start object
       command: kubectl delete -f /home/ec2-user/Service.yml   
