- hosts: demo
  become: true
  connection: ssh
  tasks: 
     - name: copy files
       copy: src=/home/ec2-user/* dest=/opt
     - name: start objects
       command: kubectl apply -f Deployment.yml
     - name: start object
       command: kubectl apply -f Service.yml    
